name: DevSecOps Pipeline

on:
  push:
    branches:
      - main-vulnerable
      - main-secure

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm ci

    - name: SAST - ESLint Security Scan
      run: npx eslint . --max-warnings 0

    - name: Verificar ejecución básica
      run: echo "Pipeline funcionando correctamente"

