name: Vulnerable CI Pipeline

on:
  push:
    branches:
      - main-vulnerable

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run SAST (npm audit FAIL expected)
        run: npm audit --audit-level=high